/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicafinal1ev;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/**
 *
 * @author Junior
 */
public class Formulario extends javax.swing.JFrame {

    MakeXpath ventanaXpath = new MakeXpath();
    MakeJAxbSax ventanaJaxbSax = new MakeJAxbSax();
    int valorDeGuardado = 0; //nos permite alternar entre uno y otro para llamar al método de guardado correspondiente

    public Formulario() {
        initComponents();
        this.getContentPane().setBackground(Color.cyan);
    }

    private File abrirJFile() {
        File fichero = null;
        int rv;

        try {
            JFileChooser fc = new JFileChooser();
            //Nos impide seleccionar más de un archivo.
            fc.setMultiSelectionEnabled(false);
            fc.setDialogType(JFileChooser.OPEN_DIALOG);
            rv = fc.showOpenDialog(this);

            if (rv == JFileChooser.APPROVE_OPTION) {
                fichero = fc.getSelectedFile();
            }
        } catch (NullPointerException e) {
            System.out.println("No se puedo mostrar el xml");
            return null;
        }

        return fichero;

    }

    private File guardarJFile() {
        File fichero = null;
        int rv;

        try {
            JFileChooser fc = new JFileChooser();
            //Nos impide seleccionar más de un archivo.
            fc.setMultiSelectionEnabled(false);
            fc.setDialogType(JFileChooser.SAVE_DIALOG);
            rv = fc.showSaveDialog(this);

            if (rv == JFileChooser.SAVE_DIALOG) {
                fichero = fc.getSelectedFile();
                ventanaJaxbSax.guardarMemoria_XML_JAXB(fichero);
            }
        } catch (NullPointerException e) {
            System.out.println("No se puedo mostrar el xml");
            return null;
        }

        return fichero;

    }

    private void guardaArchivo() {
        JFileChooser fc = new JFileChooser(); //Creamos un nuevo objeto fileChooser
        fc.setMultiSelectionEnabled(false); //Nos impide seleccionar más de un archivo.
        fc.setDialogType(JFileChooser.OPEN_DIALOG); //Abrimos el fileChooser
        //En un int guardamos el valor que nos da cuando el usuario elige un archivo
        int seleccion = fc.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            //Si llego aquí es que el usuario ha pulsado en guardar cuando ha salido el menú de jFileChooser.
            //Tenemos la opción de guardar el contenido sobre un fichero.
            File archivo = fc.getSelectedFile(); //Obtiene el archivo seleccionado
            String nombre = archivo.getName(); //Obtiene el nombre del archivo seleccionado
            //Necesitamos saber si es un png o un jpg. La extensión, para poder guardarlo y que no de error.
            //Para ello declaramos un string y tomamos un substring del nombre del archivo, tomando como referencia
            //el lastIndex del punto +1. Esto es para que no dé error.
            String extension = nombre.substring(nombre.lastIndexOf('.') + 1);
            //Si la extensión es xml, ejecuta.
            if (extension.equalsIgnoreCase("xml")) {
                System.out.println("Ha entrado");
                if (valorDeGuardado == 1) {  //Esto nos va a permitir alternar entre uno u otro dependiendo
                    ventanaJaxbSax.guardarDomComoFile(nombre);  //de si hemos usado JaxB o Dom para generar los datos.
                } else if (valorDeGuardado == 2) {       //El valor se asigna cuandos se usa el botón de añadir datos
                    ventanaJaxbSax.guardarMemoria_XML_JAXB(archivo);      //o el de editar datos.
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelDeTexto = new javax.swing.JTextPane();
        BotonEjecutarXml = new javax.swing.JButton();
        MostradorDePanorama = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        anio = new javax.swing.JTextField();
        potencia = new javax.swing.JTextField();
        combustible = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        seguridad = new javax.swing.JTextField();
        traccion = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BlocDeConsultas = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotonEjecutarXml1 = new javax.swing.JButton();
        BotonEjecutarXml2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combustible1 = new javax.swing.JTextField();
        precio1 = new javax.swing.JTextField();
        seguridad1 = new javax.swing.JTextField();
        traccion1 = new javax.swing.JTextField();
        tipo1 = new javax.swing.JTextField();
        peso1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        modelo1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        marca1 = new javax.swing.JTextField();
        anio1 = new javax.swing.JTextField();
        potencia1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        filtrarModelo = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 0, 0));

        jScrollPane1.setViewportView(panelDeTexto);

        BotonEjecutarXml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicafinal1ev/run (1) (1).jpg"))); // NOI18N
        BotonEjecutarXml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonEjecutarXmlMousePressed(evt);
            }
        });
        BotonEjecutarXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEjecutarXmlActionPerformed(evt);
            }
        });

        marca.setForeground(new java.awt.Color(153, 153, 153));
        marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marca.setText("MARCA");

        anio.setForeground(new java.awt.Color(153, 153, 153));
        anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anio.setText("AÑO DE SALIDA");

        potencia.setForeground(new java.awt.Color(153, 153, 153));
        potencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        potencia.setText("POTENCIA");

        combustible.setForeground(new java.awt.Color(153, 153, 153));
        combustible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        combustible.setText("COMBUSTIBLE");

        precio.setForeground(new java.awt.Color(153, 153, 153));
        precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precio.setText("PRECIO");

        seguridad.setForeground(new java.awt.Color(153, 153, 153));
        seguridad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seguridad.setText("NIVEL DE SEGURIDAD");

        traccion.setForeground(new java.awt.Color(153, 153, 153));
        traccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        traccion.setText("TRACCION");

        tipo.setForeground(new java.awt.Color(153, 153, 153));
        tipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipo.setText("TIPO");

        peso.setForeground(new java.awt.Color(153, 153, 153));
        peso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        peso.setText("PESO");

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAMPOS PARA MODIFICAR");

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        campoBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoBusqueda.setText("MODELO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("FILTRAR POR:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BlocDeConsultas.setColumns(20);
        BlocDeConsultas.setRows(5);
        jScrollPane2.setViewportView(BlocDeConsultas);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RunXpath");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("RunSax");

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        BotonEjecutarXml1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicafinal1ev/run (1) (1).jpg"))); // NOI18N
        BotonEjecutarXml1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonEjecutarXml1MousePressed(evt);
            }
        });
        BotonEjecutarXml1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEjecutarXml1ActionPerformed(evt);
            }
        });

        BotonEjecutarXml2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicafinal1ev/images_1.png"))); // NOI18N
        BotonEjecutarXml2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonEjecutarXml2MousePressed(evt);
            }
        });
        BotonEjecutarXml2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEjecutarXml2ActionPerformed(evt);
            }
        });

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        combustible1.setForeground(new java.awt.Color(153, 153, 153));
        combustible1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        combustible1.setText("COMBUSTIBLE");

        precio1.setForeground(new java.awt.Color(153, 153, 153));
        precio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precio1.setText("PRECIO");

        seguridad1.setForeground(new java.awt.Color(153, 153, 153));
        seguridad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seguridad1.setText("NIVEL DE SEGURIDAD");

        traccion1.setForeground(new java.awt.Color(153, 153, 153));
        traccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        traccion1.setText("TRACCION");

        tipo1.setForeground(new java.awt.Color(153, 153, 153));
        tipo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipo1.setText("TIPO");

        peso1.setForeground(new java.awt.Color(153, 153, 153));
        peso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        peso1.setText("PESO");

        jLabel14.setBackground(new java.awt.Color(153, 153, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("AÑADIR CAMPOS");

        modelo1.setForeground(new java.awt.Color(153, 153, 153));
        modelo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modelo1.setText("MODELO");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("INSERTAR");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });

        marca1.setForeground(new java.awt.Color(153, 153, 153));
        marca1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marca1.setText("MARCA");

        anio1.setForeground(new java.awt.Color(153, 153, 153));
        anio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anio1.setText("AÑO DE SALIDA");

        potencia1.setForeground(new java.awt.Color(153, 153, 153));
        potencia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        potencia1.setText("POTENCIA");

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("GUARDAR");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
        });

        jRadioButton1.setText("Filtra por modelo");

        jRadioButton2.setText("Muestra la marca");

        jRadioButton3.setText("Muestra el precio");

        jRadioButton4.setText("Muestra peso");

        filtrarModelo.setText("Tipo de Modelo");

        jRadioButton5.setText("Muestra todo los datos de coche");

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jMenu1.setText("ABRIR ");

        jMenuItem1.setText("AbrirSax");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("AbrirXpath");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoBusqueda))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(seguridad)
                                            .addComponent(combustible, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(marca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(traccion)
                                            .addComponent(anio)
                                            .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(potencia, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(peso)
                                            .addComponent(tipo)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(seguridad1)
                                            .addComponent(combustible1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(marca1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(traccion1)
                                            .addComponent(anio1)
                                            .addComponent(precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(potencia1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(peso1)
                                            .addComponent(tipo1)
                                            .addComponent(modelo1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BotonEjecutarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BotonEjecutarXml2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MostradorDePanorama, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(709, 721, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jRadioButton4)
                                            .addComponent(jRadioButton5))
                                        .addGap(205, 205, 205))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jRadioButton2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filtrarModelo)))
                                        .addGap(34, 34, 34)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonEjecutarXml1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MostradorDePanorama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(traccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(campoBusqueda)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(anio1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(potencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(combustible1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(seguridad1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(traccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BotonEjecutarXml2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonEjecutarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addGap(113, 113, 113)
                            .addComponent(jButton1))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(filtrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEjecutarXml1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEjecutarXmlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEjecutarXmlMousePressed
        panelDeTexto.setText(ventanaJaxbSax.recorrerSAX(ventanaJaxbSax.sh, ventanaJaxbSax.parser));

    }//GEN-LAST:event_BotonEjecutarXmlMousePressed

    private void BotonEjecutarXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEjecutarXmlActionPerformed

    }//GEN-LAST:event_BotonEjecutarXmlActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        File fichero = abrirJFile();
        int gestorSaxJax = ventanaJaxbSax.abrir_XML_SAX(fichero);

        ventanaJaxbSax.abrir_XML_JAXB();

        if (gestorSaxJax == 0) {
            MostradorDePanorama.setText("Se ha obtenido el SAX");
        } else if (gestorSaxJax == -1) {
            MostradorDePanorama.setText("No se ha podido el SAX");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        File fichero = abrirJFile();
        int gestorDom = ventanaXpath.abrirDOM(fichero);

        if (gestorDom == 0) {
            jLabel1.setText("Se ha obtenido el XPATH");
        } else if (gestorDom == -1) {
            jLabel1.setText("No se ha podido el XPATH");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void BotonEjecutarXml2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEjecutarXml2MousePressed
        guardarJFile();
    }//GEN-LAST:event_BotonEjecutarXml2MousePressed

    private void BotonEjecutarXml2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEjecutarXml2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEjecutarXml2ActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        ventanaJaxbSax.abrir_XML_JAXB(); //Abrimos el fichero usando JaxB para poder trabajar con él
        String busqueda = campoBusqueda.getText();

        for (int i = 0; i < ventanaJaxbSax.Cochecito.size(); i++) {

            if (ventanaJaxbSax.Cochecito.get(i).getModelo().equals(busqueda)) {
                marca.setText(ventanaJaxbSax.Cochecito.get(i).getMarca());
                campoBusqueda.setText(ventanaJaxbSax.Cochecito.get(i).getModelo());
                anio.setText(ventanaJaxbSax.Cochecito.get(i).getAnioSalida());
                potencia.setText(ventanaJaxbSax.Cochecito.get(i).getPotencia());
                combustible.setText(ventanaJaxbSax.Cochecito.get(i).getCombustible());
                precio.setText(ventanaJaxbSax.Cochecito.get(i).getPrecio());
                peso.setText(ventanaJaxbSax.Cochecito.get(i).getPeso());
                seguridad.setText(ventanaJaxbSax.Cochecito.get(i).getEstrellasSeguridad());
                traccion.setText(ventanaJaxbSax.Cochecito.get(i).getTraccion());
                tipo.setText(ventanaJaxbSax.Cochecito.get(i).getTipoChasis());

            }
        }

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed

        File fichero = abrirJFile();
        String marca = marca1.getText();
        String modelo = modelo1.getText();
        String anio = anio1.getText();
        String potencia = potencia1.getText();
        String combustible = combustible1.getText();
        String precio = precio1.getText();
        String peso = peso1.getText();
        String seguridad = seguridad1.getText();
        String traccion = traccion1.getText();
        String tipo = tipo1.getText();
        //Guardamos el valor que nos devuelve el método abrirDom en esta variable int
        int temp = ventanaJaxbSax.abrirDom(fichero);
        String datos = ""; //Nos va a permitir sacar el DOM con la inserción por pantalla para comprobar que se ha hecho correctamente
        //Si el método abrirDom nos devuelve 0, procesamos el contenido del árbol y lo mostramos.
        if (temp == 0) {
            //Añadimos un nuevo elemento perro al árbol DOM.
            ventanaJaxbSax.annadirDom(marca, modelo, anio, potencia, combustible, precio, peso, seguridad, traccion, tipo);
            //En el String datos guardamos el contenido del árbol
            datos = ventanaJaxbSax.recorrerDom();
            panelDeTexto.setText(datos); //Sacamos el contenido del árbol por pantalla
        } else if (temp == -1) {
            panelDeTexto.setText("No se puede mostrar el contenido del árbol");
        }
        //Habilitamos el botón de guardado para que se permita su uso una vez insertados los datos.
        valorDeGuardado = 1;
    }//GEN-LAST:event_jLabel16MousePressed

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        guardaArchivo();
    }//GEN-LAST:event_jLabel19MousePressed

    private void BotonEjecutarXml1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEjecutarXml1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEjecutarXml1ActionPerformed

    private void BotonEjecutarXml1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEjecutarXml1MousePressed
        //        String texto = BlocDeConsultas.getText();
        //        ventanaXpath.EjecutaXPath(texto);
        //
        //        panelDeTexto.setText(ventanaXpath.EjecutaXPath(texto));
        File fichero = abrirJFile();
        String consulta = ""; //Aquí vamos a guardar el parámetro de entrada que le vamos a pasar.
        String verModelo = filtrarModelo.getText();  //Variable que vamos a usar en la consulta
        int temp = ventanaJaxbSax.abrirDom(fichero);
        //Creamos una estructura con el árbol DOM y, si se crea correctamente, ejecutamos el XPath
        if (temp == 0) {
            //A través de los ifs seleccionamos lo que ocurre dependiendo del botón que esté seleccionado.
            if (jRadioButton5.isSelected()) {
                consulta = "/coches/coche"; //Damos un valor a la variable consulta
                try {
                    panelDeTexto.setText(ventanaXpath.EjecutaXPath(consulta, fichero)); //Se ejecuta el método del XPath y aparece en el textArea
                } catch (ParserConfigurationException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SAXException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (jRadioButton2.isSelected()) {
                consulta = "/coches/coche/@marca";
                try {
                    panelDeTexto.setText(ventanaXpath.EjecutaXPath(consulta, fichero));
                } catch (ParserConfigurationException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SAXException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (jRadioButton3.isSelected()) {
                consulta = "/coches/coche/precio";
                try {
                    panelDeTexto.setText(ventanaXpath.EjecutaXPath(consulta, fichero));
                } catch (ParserConfigurationException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SAXException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (jRadioButton4.isSelected()) {
                consulta = "/coches/coche/peso";
                try {
                    panelDeTexto.setText(ventanaXpath.EjecutaXPath(consulta, fichero));
                } catch (ParserConfigurationException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SAXException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (jRadioButton1.isSelected()) {
                consulta = "/coches/coche[./modelo='" + verModelo + "']"; //Obtenemos el valor escrito en el textfield y
                try {
                    panelDeTexto.setText(ventanaXpath.EjecutaXPath(consulta, fichero));    //se lo asignamos al string que asignamos como valor
                } catch (ParserConfigurationException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SAXException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                panelDeTexto.setText(ventanaXpath.EjecutaXPath(consulta, fichero));
            } catch (ParserConfigurationException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SAXException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (temp == -1) {
            panelDeTexto.setText("No se puede mostrar el contenido del árbol");
        }
    }//GEN-LAST:event_BotonEjecutarXml1MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // Botón que controla las modificaciones con JAXB
        //Obtenemos los datos de los textareas.
        String marca = marca1.getText();
        String modelo = modelo1.getText();
        String anio = anio1.getText();
        String potencia = potencia1.getText();
        String combustible = combustible1.getText();
        String precio = precio1.getText();
        String peso = peso1.getText();
        String seguridad = seguridad1.getText();
        String traccion = traccion1.getText();
        String tipo = tipo1.getText();
        //Guardamos el valor int que nos devuelve JaxB en un int.
        int valor = ventanaJaxbSax.editarJaxB(marca, modelo, anio, potencia, combustible, precio, peso, seguridad, traccion, tipo);
        //Si el valor del int es 0.
        if (valor == 0) {
            String aux[] = ventanaJaxbSax.recorrerJaxB(precio); //Recorre JaxB y nos lo guarda en un array de strings, pasándole el chip como parámetro.
            String salida = ""; //Declaramos un String que nos va a permitir visualizar el contenido por pantalla
            for (int i = 0; i < 10; i++) {
                salida = salida + "\n" + aux[i];  //A través de este bucle for guardamos el contenido del array en
            }                                   //un String.
            panelDeTexto.setText(salida); //Sacamos el String por pantalla.
        } else if (valor == -1) {
            panelDeTexto.setText("No se ha podido editar");
        }

        //Vamos a colocar los valores en 0 y reiniciar. Así el usuario puede hacer inserciones nuevas sin problema
        //Limpiamos los textFields.
        this.marca.setText("");
        this.anio.setText("");
        this.potencia.setText("");
        this.potencia.setText("");
        this.combustible.setText("");
        this.precio.setText("");
        this.peso.setText("");
        this.seguridad.setText("");
        this.traccion.setText("");
        this.tipo.setText("");
        //Le damos valor al int para poder proceder al guardado.
        valorDeGuardado = 2;
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BlocDeConsultas;
    private javax.swing.JButton BotonEjecutarXml;
    private javax.swing.JButton BotonEjecutarXml1;
    private javax.swing.JButton BotonEjecutarXml2;
    private javax.swing.JLabel MostradorDePanorama;
    private javax.swing.JTextField anio;
    private javax.swing.JTextField anio1;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JTextField combustible;
    private javax.swing.JTextField combustible1;
    private javax.swing.JTextField filtrarModelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField marca1;
    private javax.swing.JTextField modelo1;
    private javax.swing.JTextPane panelDeTexto;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField peso1;
    private javax.swing.JTextField potencia;
    private javax.swing.JTextField potencia1;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField precio1;
    private javax.swing.JTextField seguridad;
    private javax.swing.JTextField seguridad1;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField tipo1;
    private javax.swing.JTextField traccion;
    private javax.swing.JTextField traccion1;
    // End of variables declaration//GEN-END:variables
}
